// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as AppService from "./appservice.js";
import * as GreetService from "./greetservice.js";
export {
    AppService,
    GreetService
};
