// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * 根据key获取配置项
 */
export function GetAppConfig(key: string): $CancellablePromise<string> {
    return $Call.ByID(1146855295, key);
}

/**
 * 获取应用语言
 */
export function GetLanguage(): $CancellablePromise<string> {
    return $Call.ByID(3324446564);
}

/**
 * 设置或更新配置项
 */
export function SetAppConfig(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(1859547083, key, value);
}

/**
 * 设置应用语言
 */
export function SetLanguage(lang: string): $CancellablePromise<void> {
    return $Call.ByID(1401932280, lang);
}
