// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../database/sql/models.js";

export class SuiStore {
    "DB": sql$0.DB | null;

    /** Creates a new SuiStore instance. */
    constructor($$source: Partial<SuiStore> = {}) {
        if (!("DB" in $$source)) {
            this["DB"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SuiStore instance from a string or object.
     */
    static createFrom($$source: any = {}): SuiStore {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("DB" in $$parsedSource) {
            $$parsedSource["DB"] = $$createField0_0($$parsedSource["DB"]);
        }
        return new SuiStore($$parsedSource as Partial<SuiStore>);
    }
}

// Private type creation functions
const $$createType0 = sql$0.DB.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
